config/routes.rb
Rails.application.routes.draw do

  root 'galleries#home'

  resources :galleries do
    resources :share, only: [:new, :create]
    resources :photos do
      resources :share, only: [:new, :create]
    end
  end
  resources :users

  get    '/login'                           => 'sessions#new',       as: :login
  post   '/login'                           => 'sessions#create'
  delete '/logout'                          => 'sessions#destroy',   as: :logout
  get    '/galleries'                       => 'galleries#index',    as: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy

  mount_uploader :alt_image, AltImageUploader

  validates :title, :summary, presence: true

  def is_owner?(this_user)
    user == this_user
  end

  def cover_image(version = :standard)
    if alt_image?
      alt_image.versions[version].url
    elsif !main_image.blank?
      main_image
    else
      FFaker::Book.cover
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :gallery
  has_one :user, through: :gallery

  mount_uploader :photo, PhotoUploader

  default_scope {order ('created_at ASC') }

  validates :name, :caption, presence: true


  def is_owner?(this_user)
    user == this_user
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :galleries
  has_many :photos, through: :galleries

  has_secure_password

  mount_uploader :profile_pic, UserUploader

  validates :name, :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :avatar, require: false

  def to_s
    username
  end

  def personage(version = :standard)
    if profile_pic?
      profile_pic.versions[version].url
    elsif !avatar.blank?
      avatar
    else
      FFaker::Avatar.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless current_user
      flash[:warning] = "You need to be logged in to do this!"
      redirect_to :root unless current_user
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :load_gallery, only: [:edit, :show, :update]
  before_action :require_user, only: [:new, :edit, :update]
  before_action :is_owner, only: [:destroy]

  def index
    if current_user
      @galleries = current_user.galleries
      @gallery = Gallery.new unless @galleries.any?
    else
      @galleries = Gallery.order(created_at: :desc).page(params[:page])
      @users = User.joins(:galleries).order(created_at: :desc).limit(5)
      render 'galleries/index.html.erb'
    end
  end

  def home
    @gallery = Gallery.order('created_at desc').first
    render 'galleries/home.html.erb'
  end

  def new
    if current_user
      @gallery = Gallery.new
    else
      flash[:danger] = "You are not logged in."
      redirect_to :root
    end

  end

  def show
    @gallery = Gallery.includes(:photos).find(params[:id])
  end

  def edit
    # load_gallery
  end

  def update
    # load_gallery
    if @gallery.update(gallery_params)
      redirect_to @gallery
    else
      render :edit
    end
  end

  def create
    @gallery = current_user.galleries.new(gallery_params)
    if @gallery.save!
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    # load_gallery
    @gallery.destroy
    redirect_to :root
  end

  private

  def gallery_params
    params.require(:gallery).permit(:user_id, :title, :summary, :email, :main_image, :alt_image, :gallery_id)
  end

  def load_gallery
    @gallery = Gallery.find(params[:id])
  end

  def is_owner
    unless @gallery.user == current_user
      flash[:danger] = "You are not the creator of this Gallery."
      redirect_to :root
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_gallery, only: [:new, :edit, :show, :update]
  before_action :find_photo, only: [:edit, :show, :update]
  before_action :require_user, only: [:edit, :show, :update]
  before_action :is_owner, only: [:destroy]

  def index
    @photos = Photo.order(created_at: :desc).page(params[:page])
    @users = User.joins(:photos).order(created_at: :desc).limit(5)
    render 'photos/index.html.erb'
  end

  def new
    if current_user
      @gallery = Gallery.find(params[:gallery_id])
      @photo = Photo.new
    else
      flash[:danger] = "You are not logged in."
      redirect_to :root
    end
  end

  def show
    # find_photo
  end

  def edit
    # find_photo
  end

  def update
    # find_photo
    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save!
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    # find_photo
    @photo.destroy
    redirect_to :root
  end

  private

  def photo_params
    params.require(:photo).permit(:gallery_id, :photo, :image, :caption, :name, :email)
  end

  def find_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def find_photo
    @photo = Photo.find(params[:id])
  end

  def is_owner
    find_photo
    unless @photo.user == current_user
      flash[:danger] = "You are not the creator of this Photo."
      redirect_to :root
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])&.authenticate(params[:session][:password])
    if @user
      session[:user_id] = @user.id
        flash[:success] = "Welcome, #{@user.name}"
      redirect_to :index
    else
      flash[:danger] = "Username or password is incorrect. Please try again."
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/share_controller.rb
class ShareController < ApplicationController

  def new

  end

  def create
    if params[:share][:email]
      UserMailer.share(params[:id], params[:share][:email]).deliver
      # flash[:success] = "Photo was shared with "
      redirect_to @gallery
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :show, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_self, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    # find_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup(@user).deliver
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    # find_user
  end

  def update
    # find_user
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :password, :profile_pic, :email)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def require_self
    unless @user == current_user
      flash[:danger] = "You are unauthorized to change this persons details"
      redirect_to :root
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/share_helper.rb
module ShareHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@user, @gallery], html: {class: "form-horizontal"} do |form| %>
        <%= form.input  :title %>
        <%= form.input  :summary %>
        <%= form.input  :alt_image %>
        <%= form.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/galleries/_form_share.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for :share_gallery, html: {class: "form-horizontal"} do |form| %>
        <%= form.input :email %>
        <%= form.input :id, :as => :hidden, :input_html => { :value => params[:id] } %>
        <%= form.button :submit, "Share", class: "btn btn-primary gylphicon gylphicon-share" %>
      <% end %>
    </div>
  </div>
</div>

app/views/galleries/_gallery.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-8">
      <div class="media-right photo">
        <%= image_tag gallery.cover_image, class: "img-responsive", alt: gallery.title %>
      </div>
      <div class="row">
        <h1 class="home-post-title"><a href="/galleries/<%= gallery.id %>" target="_blank"><%= gallery.title.upcase %></a></h1>
        <p class="col-sm-4 hdr-p">
          <%= image_tag gallery.user.personage, class: "media-object, img-circle, avatar" %>
          <span id="user"><a href="/users/<%= gallery.user.id %>"><%= gallery.user.name %></a></span>
        </p>
        <p class="col-sm-4 date hdr-p">
          on <a class="date" href="#"><%= gallery.created_at.to_formatted_s(:long_ordinal) %></a>
        </p>
      </div>
      <div class="row p-top media-body" id="p-no-margin">
        <p>
          <%= simple_format(gallery.summary) %>
        </p>
      </div>
      <div class="lw-links">
        <a href="#"><i class="glyphicon glyphicon-comment"></i><span>Read Comments</span></a>
        <a href="#"><i class="glyphicon glyphicon-cloud-upload"></i><span>Upload</span></a>
        <a href="<%=  new_gallery_share_path(gallery) %>" id="blue-a"><i class="glyphicon glyphicon-envelope" id="blue-share"></i><span>Share this gallery</span></a>
      </div>
    </div>
  </div>
  <br>
  <% if gallery.is_owner?(current_user) %>
    <%= link_to ' New Photo', new_gallery_photo_path(gallery), class: "btn btn-primary glyphicon glyphicon-plus" %> <%= link_to ' Edit', edit_gallery_path(gallery), class: "btn btn-primary glyphicon glyphicon-edit" %> <%= link_to ' Delete', @gallery, method: :delete, data: {confirm: 'Are you sure you want to delete this beautiful gallery?'}, class: "btn btn-danger glyphicon glyphicon-remove-sign" %>
  <% end %>
</div>

app/views/galleries/edit.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-8">
      <div class="row">
        <h1 class="home-post-title">Editing <%= @gallery.title %></h1>
      </div>
      <div class="row p-top" id="p-no-margin">
        <%= render 'form', post: @gallery %><br>
        <br>
        <%= link_to ' Show', @gallery, class: 'btn btn-primary glyphicon glyphicon-eye-open' %><%= link_to ' Back', galleries_path, class: 'btn btn-primary glyphicon glyphicon-arrow-left' %>
      </div>
    </div>
  </div>
</div>

app/views/galleries/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12" style="text-align:center;">
      <br>
      <br>
      <br>
      <br>
      <h1>For all of your Digital Photography Hosting needs.</h1><br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/galleries/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Galleries</h1>

  <% if @galleries.any? %>
    <%= render @galleries %>
    <br>
    <div class="col-xs-12">
      <%= link_to ' New Gallery', new_gallery_path, class: 'btn btn-primary glyphicon glyphicon-plus'%>
    </div>
  <% else %>
    <div class="col-xs-12">
      You don't appear to have any galleries yet.
    </div>
    <br>
    <div class="col-xs-12">
      <%= link_to ' New Gallery', new_gallery_path, class: 'btn btn-primary glyphicon glyphicon-plus'%>
    </div>
  <% end %>
</div>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', post: @gallery %>

<%= link_to ' Back', galleries_path, class: 'btn btn-primary glyphicon glyphicon-arrow-left' %>

app/views/galleries/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @gallery.title %></h1>
      <%= simple_format @gallery.summary %>
    </div>
  </div>
  <div class="row">
    <%= render @gallery.photos %>
  </div>
  <br>
  <br>
  <%= link_to ' Back', galleries_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galleria De Fotos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <header>
        <div class="navbar-header top-menu text-left nav-pad-lt">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path , class: "navbar-brand" do %>
            <%= image_tag "logo.png", class: "media-object logo" %>
          <% end %>
          <a class="navbar-brand" href="#">Galleria De Fotos</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a class="a-pad" href="#">About</a></li>
            <% if current_user %>
              <li><%= link_to ' New Gallery', new_gallery_path, class: "btn btn-primary glyphicon glyphicon-plus" %></li>
              <li><%= link_to ' Logout', logout_path, method: :delete, class: "btn btn-danger glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to ' Signup', new_user_path, class: "btn btn-primary" %></li>
              <li><%= link_to ' Login', login_path, class: "btn btn-primary glyphicon glyphicon-log-in" %></li>
            <% end %>
            <form class="navbar-form navbar-right">
              <div class="form-group has-feedback search">
                <input type="text" class="form-control" placeholder="Search">
                <i class="glyphicon glyphicon-search form-control-feedback search-icon"></i>
              </div>
            </form>
          </ul>
        </div>
        <div class="row text-center hdr-main">
          <h1>Galleria De Fotos</h1>
        </div>
      </header>
    </div>
  </nav>
  <% if flash.any? %>
    <% flash.each do |status, message| %>
      <div class="alert alert-<%= status %>" role="alert">
        <p>
          <%= message %>
        </p>
      </div>
    <% end %>
  <% end %>
  <%= yield %>
<!-- footer -->
<footer>
  <div class="footer">
      <div class="container footer-style">
          <div class="row">
              <div class="col-sm-1 footer-nav">
                <%= image_tag "tiy-logo.png", class: "media-object" %>
              </div>
              <div class="col-sm-5 footer-nav">
                 The Ironyard Copyright 2013, All Rights Reserved.
              </div>
              <div class="col-sm-6 footer-nav text-right nav">
                  <a href="#">Nav Item 1</a> | <a href="#">Nav Item 2</a> | <a href="#">Nav Item 3</a> | <a href="#">Nav Item 4</a>
              </div>
            </div>
        </div>
    </div>
  </footer>
</body>
</html>

app/views/photos/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@gallery, @photo], html: {class: "form-horizontal"} do |form| %>
        <%= form.input  :name %>
        <%= form.input  :caption %>
        <%= form.input  :photo %>
        <%= form.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/_form_share.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for :share_photo, html: {class: "form-horizontal"} do |form| %>
        <%= form.input :email %>
        <%= form.input :id, :as => :hidden, :input_html => { :value => params[:gallery_id] } %>
        <%= form.button :submit, "Share", class: "btn btn-primary gylphicon gylphicon-share" %>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/_photo.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-8">
      <div class="row media-body photo">
        <%= image_tag photo.image, class: "img-responsive", alt: photo.name %>
      </div>
      <div class="row">
        <h1 class="home-post-title"><a href="/galleries/<%= photo.gallery_id %>/photos/<%= photo.id %>" target="_blank"><%= photo.name %></a></h1>
        <p class="col-sm-4 hdr-p">
          <%= image_tag photo.user.personage, class: "media-object, img-circle, avatar" %>
          <span id="user"><a href="/users/<%= photo.user.id %>"><%= photo.user.name %></a></span>
        </p>
        <p class="col-sm-4 date hdr-p">
          on <a class="date" href="#"><%= photo.created_at.to_formatted_s(:long_ordinal) %></a>
        </p>
      </div>
      <div class="row p-top media-body" id="p-no-margin">
        <p>
          <%= simple_format(photo.caption) %>
        </p>
      </div>
      <div class="lw-links">
        <a href="<%= new_gallery_photo_share_path(@gallery, photo) %>" id="blue-a"><i class="glyphicon glyphicon-envelope" id="blue-share"></i><span>Share this photo</span></a>
        <% if photo.is_owner?(current_user) %>
          <%= link_to ' Edit', edit_gallery_photo_path(@gallery, photo), class: "btn btn-primary glyphicon glyphicon-edit" %> <%= link_to ' Delete', gallery_photo_path(@gallery, photo), method: :delete, data: {confirm: 'Are you sure you want to delete this beautiful photo?'}, class: "btn btn-danger glyphicon glyphicon-remove-sign" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/_photoShow.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-8">
      <div class="row media-body photo">
        <%= image_tag @photo.image, class: "img-responsive", alt: @photo.name %>
      </div>
      <div class="row">
        <h1 class="home-post-title"><%= @photo.name %></h1>
        <p class="col-sm-4 hdr-p">
          <%= image_tag @photo.user.personage, class: "media-object, img-circle, avatar" %>
          <span id="user"><a href="/users/<%= @photo.user.id %>"><%= @photo.user.name %></a></span>
        </p>
        <p class="col-sm-4 date hdr-p">
          on <a class="date" href="#"><%= @photo.created_at.to_formatted_s(:long_ordinal) %></a>
        </p>
      </div>
      <div class="row p-top media-body" id="p-no-margin">
        <p>
          <%= simple_format(@photo.caption) %>
        </p>
      </div>
      <div class="lw-links">
        <a href="<%= new_gallery_photo_share_path(@gallery, @photo) %>" id="blue-a"><i class="glyphicon glyphicon-envelope" id="blue-share"></i><span>Share this photo</span></a>
        <% if @photo.is_owner?(current_user) %>
          <%= link_to ' Edit', edit_gallery_photo_path(@gallery, @photo), class: "btn btn-primary glyphicon glyphicon-edit" %> <%= link_to ' Delete', gallery_photo_path(@gallery, @photo), method: :delete, data: {confirm: 'Are you sure you want to delete this beautiful photo?'}, class: "btn btn-danger glyphicon glyphicon-remove-sign" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-8">
      <div class="row">
        <h1 class="home-post-title">Editing <%= @photo.name %></h1>
      </div>
      <div class="row p-top" id="p-no-margin">
        <%= render 'form', post: @photo %><br>
        <br>
        <%= link_to ' Show', [@gallery, @photo], class: 'btn btn-primary glyphicon glyphicon-eye-open' %><%= link_to ' Back', gallery_photos_path, class: 'btn btn-primary glyphicon glyphicon-arrow-left' %>
      </div>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Photos</h1>
  <%= paginate @photos %>


  <% @photos.each do |photo| %>
    <% render partial: "photos/photo", locals: {post: photo} %>
  <% end %>

  <%= render @photos %>

  <%= paginate @photos %>
  <br>
  <div class="col-xs-12">
    <%= link_to 'New Photo', new_photo_path %>
  </div>
</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', post: @photo %>

<%= link_to ' Back', gallery_path(params[:gallery_id]), class: "btn btn-primary glyphicon glyphicon-arrow-left" %>

app/views/photos/show.html.erb
<%= render partial: "photoShow" %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to ' Back', gallery_path(@gallery), class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
    </div>
  </div>
</div>

app/views/share/_form_share_gallery.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for :share_gallery, html: {class: "form-horizontal"} do |form| %>
        <%= form.input :email %>
        <%= form.input :id, :as => :hidden, :input_html => { :value => params[:id] } %>
        <%= form.button :submit, "Share", class: "btn btn-primary gylphicon gylphicon-share" %>
      <% end %>
    </div>
  </div>
</div>

app/views/share/_form_share_photo.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for :share_photo, html: {class: "form-horizontal"} do |form| %>
        <%= form.input :email %>
        <%= form.input :id, :as => :hidden, :input_html => { :value => params[:gallery_id] } %>
        <%= form.button :submit, "Share", class: "btn btn-primary gylphicon gylphicon-share" %>
      <% end %>
    </div>
  </div>
</div>

app/views/share/new.html.erb
<h1>New Photo</h1>

<%= render 'form', post: @share %>

<%= link_to 'Back', photos_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>

app/views/share/share.html.erb
<% if @photo? %>
  <div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row section-margin section">
      <div class="col-sm-8">
        <div class="row">
          <h1 class="home-post-title">Sharing <%= @photo.name %></h1>
        </div>
        <div class="row p-top" id="p-no-margin">
          <%= render 'form_share_photo', post: @photo %><br>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row section-margin section">
      <div class="col-sm-8">
        <div class="row">
          <h1 class="home-post-title">Sharing <%= @gallery.title %></h1>
        </div>
        <div class="row p-top" id="p-no-margin">
          <%= render 'form_share_gallery', post: @gallery %><br>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @user, html: {class: "form-horizontal"} do |form| %>
        <%= form.input  :name %>
        <%= form.input  :username %>
        <%= form.input  :password %>
        <%= form.input  :email %>
        <%= form.input  :avatar %>
        <%= form.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-9">
      <!-- Main -->
      <div class="row">
        <div class="col-md-3">
          <%= image_tag @user.personage, class: "img-responsive img-circle" %>
          <% if current_user == @user %>
            <%= link_to " Edit profile", edit_user_path(@user), class: "btn btn-primary glyphicon glyphicon-edit" %>
          <% end %>
          <%= link_to ' Back', users_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
        </div>
        <div class="col-md-9">
          <h2>Name: <%= @user.name %></h2>
          <h3>Username: <%= @user.username %></h3>
          <% if @user.galleries.count > 0 %>
            <%= render @user.galleries %>
          <% else %>
            <div class="container">
              <p id="notice"><%= notice %></p>
              <div class="row section-margin section">
                <div class="col-sm-8">
                  <div class="row">
                    <p class="col-sm-4 hdr-p">
                      No galleries yet!
                    </p>
                    <br>
                    <br>
                    <p class="col-sm-4 hdr-p">
                      <%= link_to ' New Gallery', new_gallery_path, class: "btn btn-primary glyphicon glyphicon-plus" %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to ' Show', @user, class: 'btn btn-primary glyphicon glyphicon-user' %>
<%= link_to ' Back', users_path, class: 'btn btn-primary glyphicon glyphicon-arrow-right' %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row section-margin section">
    <div class="col-sm-9">
      <div class="row">
        <h1>Users</h1>
      </div>
      <% @users.each do |user| %>
        <div class="row">
          <div class="col-sm-3">
            <%= user.username %>
          </div>
          <div class="col-sm-2">
            <%= link_to ' Show', user, class: "btn btn-primary glyphicon glyphicon-user" %>
          </div>
          <% if current_user == user %>
            <div class="col-sm-2">
              <%= link_to ' Edit', edit_user_path(user), class: "btn btn-primary glyphicon glyphicon-edit" %>
            </div>
            <div class="col-sm-2">
              <%= link_to ' Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-remove-sign" %>
            </div>
          <% else %>
            <div class="col-sm-4"></div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <%= link_to ' New User', new_user_path, class: "btn btn-primary glyphicon glyphicon-plus" %>
  </div>
</div>
<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: "btn btn-primary glyphicon glyphicon-arrow-right" %>

app/views/users/show.html.erb
<% render partial: "user", locals: {user: @user} %>
<%= render @user %>